baseURL = 'https://dsrtechnologies.com/'
languageCode = 'en-us'
title = 'DSR Technologies Site'
theme = 'hugo-arcana'
copyright = """<p>© 2025 DSR Technologies, Inc. All rights reserved.<br>This content is the property of DSR Technologies, Inc. and is protected by copyright laws. No part of this material may be reproduced, distributed, or transmitted in any form or by any means without the prior written permission of DSR Technologies, Inc.</p>"""
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[taxonomies]
    tag = "tags"

[params]
    phone = "(352) 450-2307"
    phone_link = "tel:+13524502307"
    
    description = "A business/corporate style responsive site template."
    images = ['images/metaimage.jpg']
    show_post_dates = false


    #[[params.social]]
        #title = "Twitter"
        #icon = "fa-twitter"
        #url = "#"
    #[[params.social]]
        #title = "Facebook"
        #icon = "fa-facebook-f"
        #url = "#"
    #[[params.social]]
        #title = "GitHub"
        #icon = "fa-github"
        #url = "#"
    #[[params.social]]
        #title = "LinkedIn"
        #icon = "fa-linkedin-in"
        #url = "#"
    #[[params.social]]
        #title = "Creative Commons"
        #icon = "fa-creative-commons"
        #url = "https://creativecommons.org/"


    [params.footer]

        [[params.footer.links]]
            header = "Site Links"
        [[params.footer.links.links]]
            title = "About Us"
            url = "/about-us/"
        [[params.footer.links.links]]
            title = "Job Application"
            url = "/join-our-team/"
        [[params.footer.links.links]]
            title = "DSR Management System"
            url = "https://dsrcloud.com/#login"
        [[params.footer.links.links]]
            title = "Timeclock"
            url = "http://timeclock.dsrtechnologies.com/Login"
        #[[params.footer.links.links]]
        #    title = "Training Portal"
        #    url = "#"
        #[[params.footer.links.links]]
            #title = "ksjdhgk"
            #url = "#"
        #[[params.footer.links.links]]
            #title = "Sed et dapibus mattis"
            #url = "#"

        [[params.footer.links]]
            header = "Customer Links"
        [[params.footer.links.links]]
            title = "Monitoring Central Station"
            url = "https://myalarms.com"
        [[params.footer.links.links]]
            title = "Services Request - (Coming Soon)"
            url = "#"
        [[params.footer.links.links]]
            title = "Quote Request - (Coming Soon)"
            url = "#"
        #[[params.footer.links.links]]
        #    title = "Projects Customer Portal"
        #    url = "#"
        #[[params.footer.links.links]]
        #    title = "Training Portal"
        #    url = "#"
        #[[params.footer.links.links]]
            #title = "Sed et dapibus quis"
            #url = "#"
        #[[params.footer.links.links]]
            #title = "Rutrum amet varius"
            #url = "#"

        [[params.footer.links]]
            header = "Licensed Locations"
        [[params.footer.links.links]]
            title = "Florida"
            url = "https://www.myflorida.gov/"
        [[params.footer.links.links]]
            title = "North Carolina"
            url = "https://northcarolina.com/"
        [[params.footer.links.links]]
            title = "South Carolina"
            url = "https://sc.gov/"
        [[params.footer.links.links]]
            title = "Mississippi"
            url = "https://www.ms.gov/"
        #[[params.footer.links.links]]
            #title = "Training Portal"
            #url = "#"
        #[[params.footer.links.links]]
            #title = "Sed et dapibus quis"
            #url = "#"
        [[params.footer.links.links]]
            title = "Main Office (352) 450-2307"
            url = "tel:+13524502307"


        #[params.footer.contact_form]
            #enabled = true
            #header = "Get In Touch"
            #action = ""
